use crate::api::types::{
    ContainerInventory, CraftingRecipe, DamageWarningRule, Manny, Probe, ProbeAlert,
    ProbeInventory, ProbeMovement, SectorObservation, StorageContainer, VisitedSector,
};

pub enum ApiMessage {
    ProbeUpdated(Probe),
    ManniesUpdated(Vec<Manny>),
    SectorUpdated(SectorObservation),
    ScanError(String),
    MoveStarted(ProbeMovement),
    MoveError(String),
    RepairStarted,
    RepairError(String),
    MineStarted,
    MineError(String),
    VersionFetched(u32),
    VisitedSectorsFetched(Vec<VisitedSector>),
    JettisonDone(ProbeInventory),
    JettisonError(String),
    CraftStarted,
    CraftError(String),
    SalvageStarted,
    SalvageError(String),
    RecallStarted,
    RecallError(String),
    DeployStarted,
    DeployError(String),
    AtomicPrinterCraftStarted,
    AtomicPrinterCraftError(String),
    RecipesFetched(Vec<CraftingRecipe>),
    RenameMannyDone(Manny),
    RenameMannyError(String),
    InspectStarted,
    InspectError(String),
    RecoverStarted,
    RecoverError(String),
    DetachStarted,
    DetachError(String),
    DamageWarningsFetched(Vec<ProbeAlert>, DamageWarningRule),
    DamageWarningAcknowledged(ProbeAlert),
    AlertsFetched(Vec<ProbeAlert>),
    AlertAcknowledged(ProbeAlert),
    StorageContainersFetched(Vec<StorageContainer>),
    StorageContainerDetailFetched(StorageContainer, ContainerInventory),
    RenameContainerDone(StorageContainer, ProbeInventory),
    RenameContainerError(String),
    UpdateContainerRulesDone(StorageContainer, ProbeInventory),
    UpdateContainerRulesError(String),
    StorageMoveDone(Manny, ProbeInventory),
    StorageMoveError(String),
    DropMannyCargoStarted(Manny),
    DropMannyCargoError(String),
    DeuteriumRefuelStarted,
    DeuteriumRefuelError(String),
    MindSnapshotReassigned(Probe),
    MindSnapshotReassignError(String),
    DropStorageContainerStarted(Manny),
    DropStorageContainerError(String),
    Error(String),
}
