use crate::api::types::{
    ContainerInventory, CraftingRecipe, DamageWarningRule, Manny, Mission, Probe, ProbeAlert,
    ProbeInventory, ProbeMessage, ProbeMovement, ProbeSentMessage, ScutNetwork, SectorObservation,
    StorageContainer, VisitedSector,
};

pub enum ApiMessage {
    ProbeUpdated(Probe),
    ManniesUpdated(Vec<Manny>),
    SectorUpdated(SectorObservation),
    ScanError(String),
    MoveStarted(ProbeMovement),
    MoveError(String),
    RepairStarted,
    RepairError(String),
    MineStarted,
    MineError(String),
    VersionFetched(u32),
    VisitedSectorsFetched(Vec<VisitedSector>),
    JettisonDone(ProbeInventory),
    JettisonError(String),
    CraftStarted,
    CraftError(String),
    SalvageStarted,
    SalvageError(String),
    RecallStarted,
    RecallError(String),
    DeployStarted,
    DeployError(String),
    AtomicPrinterCraftStarted,
    AtomicPrinterCraftError(String),
    RecipesFetched(Vec<CraftingRecipe>),
    RenameMannyDone(Manny),
    RenameMannyError(String),
    InspectStarted,
    InspectError(String),
    RecoverStarted,
    RecoverError(String),
    DetachStarted,
    DetachError(String),
    DamageWarningsFetched(Vec<ProbeAlert>, DamageWarningRule),
    DamageWarningAcknowledged(ProbeAlert),
    AlertsFetched(Vec<ProbeAlert>),
    AlertAcknowledged(ProbeAlert),
    StorageContainersFetched(Vec<StorageContainer>),
    StorageContainerDetailFetched(StorageContainer, ContainerInventory),
    StorageContainerDetailError(String),
    RenameContainerDone(StorageContainer, ProbeInventory),
    RenameContainerError(String),
    UpdateContainerRulesDone(StorageContainer, ProbeInventory),
    UpdateContainerRulesError(String),
    StorageMoveDone(Manny, ProbeInventory),
    StorageMoveError(String),
    DropMannyCargoStarted(Manny),
    DropMannyCargoError(String),
    DeuteriumRefuelStarted,
    DeuteriumRefuelError(String),
    MindSnapshotReassigned(Probe),
    MindSnapshotReassignError(String),
    MissionsFetched(Vec<Mission>),
    MissionAbandoned(Mission),
    MissionAbandonError(String),
    ScutRelayTurnedOn,
    ScutRelayTurnOnError(String),
    ScutNetworkFetched(ScutNetwork),
    ScutNetworkError(String),
    MessagesFetched(Vec<ProbeMessage>),
    SentMessagesFetched(Vec<ProbeSentMessage>),
    MessageSent(ProbeMessage),
    MessageSendError(String),
    MessageMarkedRead(ProbeMessage),
    DropStorageContainerStarted(Manny),
    DropStorageContainerError(String),
    /// A direct user action (ack alert / damage warning, mark message read) that
    /// failed — surfaced in the status bar so the key does not feel dead.
    /// Distinct from `Error`, which is the fatal-probe channel that drives
    /// refresh backoff.
    ActionError(String),
    Error(String),
}
